# Afficher une valeur float

cours = float(input("Introduisez le cours de l'EUR/USD : "))    # le fait de taper un caractère ou une chaîne de caractères suivis ...
                                                                # ... du signe = suffit pour que Python interprète qu'une variable ...
                                                                # ...est déclarée.
                                                                # Mais sans affecter de valeur ('texte' ou nombre) à cette variable ...
                                                                # ... Python renvoie un message d'erreur (not defined).
                                                                # Le fait d'affecter une valeur à cette variable après le signe = ...
                                                                # ... suffit pour que Python interprète le type de la variable.
print("Le cours de l'EUR/USD est ",cours)